#!/usr/bin/env bash
# One GPU, three jobs, in the order the paper needs them, as one chain:
#   1. G13 held pair, v3 protocol, unified cell    -> the paper's Fig. 3 numbers
#   2. G15 shear ramp to 400 MPa, ctl + fld (96 ps each)
#   3. G16 dipole under the maintained field, no load, ctl + fld (60 ps each)
# (the free pair was run with the CG-only protocol on 2 Sept, 23:57)
#
# Do not edit this file while it runs: bash reads it by byte offset.
cd "$(dirname "$0")/.."
PY=.venv/Scripts/python.exe
step() { echo "[$(date +%H:%M:%S)] $*"; }
step "1/3 G13 held pair v3 (the paper's Fig. 3 numbers)"
$PY scripts/run_stageG13_interface100k.py --cell u100k --protocol v3 --only ctl_held,fld_held || { step "FAILED at 1/3"; exit 1; }
step "2/3 G15 shear ramp"
$PY scripts/run_stageG15_unified_dynamics.py --only G15 || { step "FAILED at 2/3"; exit 1; }
step "3/3 G16 dipole under maintained field"
$PY scripts/run_stageG15_unified_dynamics.py --only G16 --nsteps-g16 60000 || { step "FAILED at 3/3"; exit 1; }
step "queue complete"
