#!/usr/bin/env python3
"""Fixes from the multi-agent review of 4 Sept 2026 that do not depend on the
stage G15 numbers (those go through patch_round3). EN and RU drafts, plus
main_ru.tex (competing-interest statement) and splice_drafts.py."""
from __future__ import annotations
import io, re
from pathlib import Path

DR = Path(__file__).resolve().parent
PAPER = DR.parent
rep: list = []


def flex(s: str) -> str:
    return r"\s+".join(re.escape(p) for p in re.split(r"\s+", s.strip()))


def sub(t, old, new, tag):
    out, n = re.subn(flex(old), lambda m: new, t, count=1)
    if n == 0:
        rep.append(tag)
    return out


def rsub(t, pattern, new, tag, flags=re.S):
    out, n = re.subn(pattern, lambda m: new, t, count=1, flags=flags)
    if n == 0:
        rep.append(tag)
    return out


def load(name):
    return io.open(DR / name, encoding="utf-8").read()


def save(name, t):
    io.open(DR / name, "w", encoding="utf-8", newline="\n").write(t)


def strip_header(t: str) -> str:
    i = t.find("\\section{")
    return t[i:] if i > 0 else t


def swap_figures(t: str) -> str:
    """Put the fig:rss float before the fig:traj float (first citation order)."""
    def block(key):
        i = t.find(key)
        s = t.rfind("\\begin{figure}", 0, i)
        e = t.find("\\end{figure}", i) + len("\\end{figure}")
        return s, e
    ts, te = block("fig_trajectories_")
    rs, re_ = block("fig_rss_vs_thresholds_")
    if ts < 0 or rs < 0 or not (ts < rs):
        rep.append("figure-order")
        return t
    traj = t[ts:te]; rss = t[rs:re_]
    between = t[te:rs]
    return t[:ts] + rss + between + traj + t[re_:]


# ================================================================ EN
t = strip_header(load("Section_2_en.tex"))
t = sub(t, r"""and line along $y$ is
then periodic across the cell and glides in $x$ parallel to the interface,""",
        r"""and line along $y$ then spans the whole width of the cell, so that it
represents an infinitely long straight dislocation, and glides in $x$
parallel to the interface,""", "en-periodic")
t = sub(t, r"""A separate calculation of a flat layer
without the ridge was not run, so it is not assumed that a flat layer
transfers strictly zero stress to the matrix.""",
        r"""Straining the flat layer as well was tried: a layer that is periodic in its
plane cannot be sheared coherently, and holding it at the strain loaded the
whole slab uniformly by about 150~MPa (Section~\ref{sec:eigenstrain}); the
layer is therefore left unstrained and the ridge alone carries the strain.""", "en-flat")
t = rsub(t, r"Atomic\s+positions are relaxed by energy minimisation \(conjugate gradients, relative\s+energy tolerance.*?without thermal motion\.",
         r"""The control structure is relaxed in three stages: energy minimisation by
conjugate gradients (the atoms are moved to positions of minimum energy
without thermal motion), 6~ps of molecular dynamics at 300~K followed by
12~ps of cooling to 0.5~K, which relax the long-wavelength modes of the slab
that minimisation alone does not reach, and a final minimisation to a force
of 0.05~eV/\AA{} (two-norm over all atoms). The strained cell is built from
this relaxed state (Section~\ref{sec:eigenstrain}) and minimised to
0.02~eV/\AA{}.""", "en-minimisation")
t = rsub(t, r"The \\emph\{control\} cell has no strain\. It is generated by the same script.*?exact cancellation\.",
         r"""The \emph{control} cell has no strain. It is the relaxed structure of
Section~\ref{sec:cell} itself; the strained cell is built from it, minimised
with the same tolerance and compared with it atom by atom, so that the
residual lattice mismatch of Section~\ref{sec:cell}, the arrangement of the
interfacial layer and the long-wavelength strain of the slab are common to
both and cancel in the difference.""", "en-control")
t = sub(t, "the von Mises stress, the combination of the\nstress components that enters yield criteria, and the resolved shear stress,",
        "the von Mises stress, a single positive number that measures the shear\ncontent of a stress state and enters the yield criterion of a ductile metal,\nand the resolved shear stress,", "en-vm-gloss")
t = sub(t, "first averaged over a slab 4~\\AA{} thick", "first averaged over a slice 4~\\AA{} thick", "en-slab1")
t = sub(t, "the interface plane in slabs 4~\\AA{} thick", "the interface plane in slices 4~\\AA{} thick", "en-slab2")
t = sub(t, "between the strained and the control cell, slab by slab.", "between the strained and the control cell, slice by slice.", "en-slab3")
t = sub(t, r"""is set by the residual slab-to-slab scatter far from the interface: over
$r\geq60$~\AA{} the mean of $\Delta\mathrm{RSS}_{\max}$ is $0.5\pm0.6$~MPa
(mean and standard deviation over 15 slabs), the level below which no field
is resolved.""",
        r"""is set by the residual slice-to-slice scatter far from the interface: over
$r\geq60$~\AA{} the mean of $\Delta\mathrm{RSS}_{\max}$ is $2.5\pm0.5$~MPa
(mean and standard deviation over thirteen slices), the resolution of the
calculation, below which no field is resolved.""", "en-noise24")
t = sub(t, "2.19~\\AA{}", "2.22~\\AA{}", "en-minnn")
save("Section_2_en.tex", t)

t = load("Section_3_en.tex")
t = sub(t, r"""The upper panel gives the von Mises stress---a single positive number that
measures the shear content of a stress state and enters the yield criterion
of a ductile metal---in each cell.""",
        r"""The upper panel gives the von Mises stress (Section~\ref{sec:stress}) in
each cell.""", "en-vm31")
t = rsub(t, r"Here and below\s+\$\\mathrm\{RSS\}_\{\\max\}\$ denotes the shear stress resolved.*?drives dislocation motion\. It is\s+computed from the difference tensor,",
         r"$\mathrm{RSS}_{\max}$ (Section~\ref{sec:stress}) is computed from the difference tensor,", "en-rss31")
t = sub(t, r"""It falls below
10~MPa by $r\approx55$~\AA{} and below 2~MPa beyond 90~\AA{};""",
        r"""It falls below
10~MPa beyond $r\approx65$~\AA{} and below 2~MPa beyond about 95~\AA{};""", "en-coh")
t = sub(t, r"""The atomistic ridge produces a smaller stress at its surface and a flatter
profile: held rigidly on a rigid layer and infinite along $y$, it is closer
to a cylinder than to a sphere, and the two agree within a factor of two
over $d=15$--$50$~\AA{}.""",
        r"""The atomistic ridge produces a smaller stress at its surface and a flatter
profile. The smaller value is a matter of shape: a half-elliptical bump on a
flat layer radiates less into the matrix above it than a compact particle
does (a cylinder holding the same strain carries almost the same interior
stress as the sphere, 39 against 41~MPa); the flatter decay is that of a body
infinite along $y$, whose field falls off more slowly than the inverse cube
of a compact particle. Over $d=15$--$50$~\AA{} the ridge and the sphere agree
within a factor of two.""", "en-cylinder")
t = sub(t, r"""When the springs are removed and the
inclusion is free to relax, the ridge retains 0.2--0.4 of the strain and the shear
stress above the crest falls below 5~MPa: the field of Fig.~\ref{fig:sigma}
exists only as long as something holds the inclusion at its strain.""",
        r"""When the springs are removed and the inclusion is free to relax, the ridge
retains only 0.2--0.4 of the strain and the shear stress on the ridge axis
falls below 5~MPa; the two free minimisations then also differ across the
whole slab, by $10\pm3$~MPa beyond 60~\AA{} against $2.5\pm0.5$~MPa for the
held pair, because an unconstrained inclusion relaxes along the normal and
shifts the stress of the slab as a whole. The free cell therefore gives the
retained strain but no usable stress field, and the field of
Fig.~\ref{fig:sigma} exists only as long as something holds the inclusion at
its strain.""", "en-free")
t = sub(t, r"""the interface cells are built without dislocations, and the
calculation gives no sign of a plastified layer around the inclusion.""",
        r"""the interface cells are built without dislocations, and dislocation
analysis of the strained cell after minimisation finds none.""", "en-plastified")
t = sub(t, r"""the origin is set at the moment the load is switched on, after
10~ps without load""",
        r"""the displacement is measured from the position at the moment the load is
switched on, $t=10$~ps, after 10~ps without load""", "en-fig4")
t = rsub(t, r"the activation volume\s+\$V\^\{\*\}\$---the parameter of thermally activated glide.*?---",
         r"the activation volume $V^{*}$ (the volume swept by a dislocation segment as it crosses an obstacle, which sets how strongly the glide rate responds to stress)", "en-vstar33")
t = sub(t, r"""No Mg/Si clusters were constructed or
identified; the result refers to the one random solute configuration
sampled.""",
        r"""No Mg/Si clusters were constructed or identified. A second random
configuration, run only through the 45, 55 and 65~MPa rungs, was likewise
pinned at every rung it reached; the 75~MPa bound rests on the one
realization that completed the staircase.""", "en-realizations33")
t = swap_figures(t)
save("Section_3_en.tex", t)

t = load("Sections_4_en.tex")
t = sub(t, r"""Here $V^{*}$ is the activation volume: the volume
swept by the dislocation segment as it crosses the obstacle (the Burgers
vector times the area swept), which sets how strongly the jump rate responds
to stress \cite{CaillardMartin2003}.""",
        r"""Here $V^{*}$ is the activation volume of Section~\ref{sec:mobility}
\cite{CaillardMartin2003}.""", "en-vstar4")
t = sub(t, "8.7--65.2~MPa across the range of $V^{*}$", "8.4--62.7~MPa across the range of $V^{*}$", "en-taum")
t = sub(t, "The first exceeds\nthem by a factor of 3.5--7", "The first exceeds\nthem by a factor of 3.6--10", "en-factor")
t = sub(t, r"""41~MPa (the analytical sphere held at the strain of 0.194\%) or
15~MPa (the stress directly above the ridge in the interface cell,
Section~\ref{sec:sigma_r})""",
        r"""41~MPa (the surface value of the analytical sphere held at 0.194\%;
41.45 unrounded) or 15~MPa (the maximum on the ridge axis in the interface
cell, 15.45 unrounded, Section~\ref{sec:sigma_r})""", "en-tabcap")
t = sub(t, r"$b=a/\sqrt{2}=2.8638$~\AA{}", r"$b=2.8638$~\AA{}", "en-b")
t = sub(t, "about 0.49~$\\mu$m", "about 0.5~$\\mu$m", "en-bow")
t = sub(t, r"""falling to the far-field level of $2.5\pm0.5$~MPa within
80~\AA{}""", r"""falling within 80~\AA{} to $2.5\pm0.5$~MPa, the resolution of the
calculation""", "en-51far")
t = sub(t, r"""The present calculations contain only an
inclusion strained once and then relaxed; they represent neither loading with
the field on nor the state of the material after its removal.""",
        r"""The present calculations contain an inclusion held at its strain while the
matrix relaxes (the interface cell), one relaxed from it (the free cell) and
loaded cells with the ridge held or unstrained; none of them represents the
state of the material after the field has been removed.""", "en-53")
t = sub(t, r"""and its reach, 60~\AA{}, is set by the cross section of the
ridge;""", r"""and its reach---some 30~\AA{} at full strength, 80~\AA{} in all
(Section~\ref{sec:sigma_r})---is set by the cross section of the ridge;""", "en-reach")
t = sub(t, r"""The pinning result rests on one random arrangement of Mg and Si
atoms and one set of starting velocities;""",
        r"""The pinning result rests on two random arrangements of Mg and Si atoms,
only one of which completed the staircase, and one set of starting
velocities each;""", "en-realizations54")
t = sub(t, r"""averaged over slabs 4~\AA{} thick parallel to the
interface; this is an approximation whose noise level, after the six stress
components have been averaged over each slab, is $0.5\pm0.6$~MPa.""",
        r"""averaged over slices 4~\AA{} thick parallel to the
interface; this is an approximation whose resolution, after the six stress
components have been averaged over each slice, is $2.5\pm0.5$~MPa.""", "en-54noise")
save("Sections_4_en.tex", t)

# ================================================================ RU
t = strip_header(load("Section_2_ru.tex"))
t = sub(t, r"""и линией вдоль $y$ при этом периодична поперёк ячейки и скользит вдоль $x$
параллельно границе;""",
        r"""и линией вдоль $y$ при этом проходит через всю ширину ячейки, представляя
бесконечно длинную прямолинейную дислокацию, и скользит вдоль $x$
параллельно границе;""", "ru-periodic")
t = sub(t, r"""Отдельный
расчёт плоского слоя без гребня не проводился, поэтому не предполагается, что
плоский слой передаёт в матрицу строго нулевое напряжение.""",
        r"""Деформировать и плоский слой пробовали: слой, периодичный в своей
плоскости, нельзя когерентно сдвинуть, и удержание его при заданной
деформации однородно нагружало весь слой алюминия примерно на 150~МПа
(раздел~2.2); поэтому плоский слой оставлен недеформированным, и деформацию
несёт один гребень.""", "ru-flat")
t = rsub(t, r"Положения атомов\s+релаксируются минимизацией энергии \(метод сопряжённых градиентов,.*?без теплового движения\.",
         r"""Контрольная структура релаксируется в три стадии: минимизация энергии
методом сопряжённых градиентов (атомы переводятся в положения минимума
энергии без теплового движения), 6~пс молекулярной динамики при 300~К с
последующим охлаждением до 0{,}5~К за 12~пс, снимающие длинноволновые моды
слоя, недоступные одной минимизации, и заключительная минимизация до силы
0{,}05~эВ/\AA{} (2-норма по всем атомам). Деформированная ячейка строится из
этого релаксированного состояния (раздел~2.2) и минимизируется до
0{,}02~эВ/\AA{}.""", "ru-minimisation")
t = rsub(t, r"\\emph\{Контрольная\} ячейка деформации не содержит\. Она порождается тем же.*?(?=\n\n)",
         r"""\emph{Контрольная} ячейка деформации не содержит. Это сама релаксированная
структура раздела~2.1; деформированная ячейка строится из неё,
минимизируется с тем же допуском и сравнивается с ней атом за атомом, так
что остаточное несоответствие решёток раздела~2.1, состояние прослойки на
границе и длинноволновая деформация слоя общие для обеих и в разности
сокращаются. Ячейки границы дают профиль напряжений в матрице и длину его
затухания. Напряжения, при которых дислокации приходят в движение, получены
отдельно, в нагружаемых ячейках раздела~2.3, и служат лишь порогами, с
которыми сопоставляется этот профиль.""", "ru-control")
t = sub(t, r"""напряжение фон Мизеса --- комбинация
компонент напряжения, входящая в критерии текучести, ---""",
        r"""напряжение фон Мизеса --- единственное положительное число,
характеризующее сдвиговую часть напряжённого состояния и входящее в критерий
текучести пластичного металла, ---""", "ru-vm-gloss")
t = sub(t, r"""$0{,}5 \pm 0{,}6$~МПа (среднее и стандартное отклонение по 15 слоям) ---
уровень, ниже которого поле не разрешается.""",
        r"""$2{,}5 \pm 0{,}5$~МПа (среднее и стандартное отклонение по тринадцати
слоям) --- разрешающая способность расчёта, ниже которой поле не
разрешается.""", "ru-noise24")
t = sub(t, "2{,}19~\\AA{}", "2{,}22~\\AA{}", "ru-minnn")
save("Section_2_ru.tex", t)

t = load("Section_3_ru.tex")
t = sub(t, r"""Верхняя панель даёт напряжение фон Мизеса --- единственное положительное
число, характеризующее сдвиговую часть напряжённого состояния и входящее в
критерий текучести пластичного металла, --- в каждой ячейке.""",
        r"""Верхняя панель даёт напряжение фон Мизеса (раздел~2.4) в каждой ячейке.""", "ru-vm31")
t = rsub(t, r"Здесь и далее \$\\mathrm\{RSS\}_\{\\max\}\$ обозначает касательное.*?приводит дислокацию в движение\. Оно\s+вычисляется из разностного тензора,",
         r"$\mathrm{RSS}_{\max}$ (раздел~2.4) вычисляется из разностного тензора,", "ru-rss31")
t = sub(t, r"""К $r \approx 55$~\AA{} это
напряжение падает ниже 10~МПа, а за 90~\AA{} --- ниже 2~МПа;""",
        r"""За $r \approx 65$~\AA{} это напряжение падает ниже 10~МПа, а за 95~\AA{}
--- ниже 2~МПа;""", "ru-coh")
t = sub(t, r"""Атомистический
гребень даёт меньшее напряжение у своей поверхности и более пологий
профиль: жёстко удерживаемый на жёстком слое и бесконечный вдоль $y$, он
ближе к цилиндру, чем к сфере, и в интервале $d = 15$--$50$~\AA{} оба
согласуются в пределах множителя два.""",
        r"""Атомистический гребень даёт меньшее напряжение у своей поверхности и более
пологий профиль. Меньшее значение --- дело формы: полуэллиптический выступ на
плоском слое излучает в матрицу над собой меньше, чем компактная частица
(цилиндр, удерживающий ту же деформацию, несёт внутри почти то же напряжение,
что и сфера, --- 39 против 41~МПа); более пологий спад свойствен телу,
бесконечному вдоль $y$, поле которого убывает медленнее, чем обратный куб
расстояния для компактной частицы. В интервале $d = 15$--$50$~\AA{} гребень и
сфера согласуются в пределах множителя два.""", "ru-cylinder")
t = sub(t, r"""Если пружины снять и дать включению
релаксировать, гребень сохраняет 0{,}2--0{,}4 деформации, а касательное напряжение
над вершиной падает ниже 5~МПа: поле рис.~\ref{fig:sigma} существует лишь до
тех пор, пока что-то удерживает включение при его деформации.""",
        r"""Если пружины снять и дать включению релаксировать, гребень сохраняет лишь
0{,}2--0{,}4 деформации, а касательное напряжение на оси гребня падает ниже
5~МПа; при этом две свободные минимизации расходятся и по всему слою --- на
$10 \pm 3$~МПа за 60~\AA{} против $2{,}5 \pm 0{,}5$~МПа для удерживаемой
пары, поскольку ничем не стеснённое включение релаксирует вдоль нормали и
сдвигает напряжение слоя в целом. Свободный вариант, таким образом, даёт
сохранённую долю деформации, но не пригодное к использованию поле
напряжений, а поле рис.~\ref{fig:sigma} существует лишь до тех пор, пока
что-то удерживает включение при его деформации.""", "ru-free")
t = sub(t, r"""ячейки
границы построены без дислокаций, и признаков пластифицированного слоя
вокруг включения расчёт не даёт.""",
        r"""ячейки границы построены без дислокаций, и дислокационный анализ
деформированной ячейки после минимизации их не находит.""", "ru-plastified")
t = sub(t, r"""начало отсчёта --- момент включения
нагрузки после 10~пс без нагрузки""",
        r"""смещение отсчитывается от положения в момент включения нагрузки,
$t = 10$~пс, после 10~пс без нагрузки""", "ru-fig4")
t = rsub(t, r"активационный объём\s+\$V\^\{\*\}\$ --- [^.]*?---",
         r"активационный объём $V^{*}$ (объём, заметаемый сегментом дислокации при преодолении препятствия; он определяет, насколько сильно скорость скольжения откликается на напряжение)", "ru-vstar33")
t = sub(t, r"""Кластеры Mg/Si не строились и не идентифицировались; результат
относится к единственной выбранной случайной конфигурации примесных
атомов.""",
        r"""Кластеры Mg/Si не строились и не идентифицировались. Вторая случайная
конфигурация, рассчитанная только до ступеней 45, 55 и 65~МПа, точно так же
удерживала дислокацию на каждой достигнутой ступени; граница 75~МПа
опирается на ту единственную реализацию, которая прошла всю лестницу.""", "ru-realizations33")
t = swap_figures(t)
save("Section_3_ru.tex", t)

t = load("Sections_4_ru.tex")
t = sub(t, r"""Здесь $V^{*}$ --- активационный объём: объём,
заметаемый сегментом дислокации при преодолении препятствия (произведение
вектора Бюргерса на заметаемую площадь); он определяет, насколько сильно
частота скачков откликается на напряжение [18].""",
        r"""Здесь $V^{*}$ --- активационный объём раздела~3.3 [18].""", "ru-vstar4")
t = sub(t, "8{,}7--65{,}2~МПа во всём интервале $V^{*}$", "8{,}4--62{,}7~МПа во всём интервале $V^{*}$", "ru-taum")
t = sub(t, "Первое превышает их в 3{,}5--7 раз", "Первое превышает их в 3{,}6--10 раз", "ru-factor")
t = sub(t, r"""41~МПа
(аналитическая сфера, удерживаемая при деформации
0{,}194\%) или 15~МПа (напряжение непосредственно над гребнем в ячейке границы,
раздел~3.1)""",
        r"""41~МПа (значение на поверхности аналитической сферы, удерживаемой при
0{,}194\%; 41{,}45 без округления) или 15~МПа (максимум на оси гребня в
ячейке границы, 15{,}45 без округления, раздел~3.1)""", "ru-tabcap")
t = sub(t, "около\n0{,}49~мкм", "около 0{,}5~мкм", "ru-bow")
t = sub(t, r"""со спадом до уровня дальнего поля $2{,}5\pm0{,}5$~МПа в пределах 80~\AA{}""",
        r"""со спадом в пределах 80~\AA{} до $2{,}5\pm0{,}5$~МПа --- разрешающей
способности расчёта""", "ru-51far")
t = sub(t, r"""Настоящие расчёты содержат лишь включение, деформированное
однократно и затем релаксированное; они не представляют ни нагружения при
включённом поле, ни состояния материала после его снятия.""",
        r"""Настоящие расчёты содержат включение, удерживаемое при своей деформации,
пока релаксирует матрица (ячейка границы), включение, релаксировавшее из
него (свободный вариант), и нагружаемые ячейки с удерживаемым или
недеформированным гребнем; ни одна из них не представляет состояния
материала после снятия поля.""", "ru-53")
t = sub(t, r"""а его дальность, 60~\AA{}, задаётся
сечением гребня:""", r"""а его дальность --- около 30~\AA{} в полную силу и 80~\AA{} в целом
(раздел~3.1) --- задаётся сечением гребня:""", "ru-reach")
t = sub(t, r"""Результат по закреплению опирается на одно случайное расположение атомов Mg и
Si и один набор начальных скоростей;""",
        r"""Результат по закреплению опирается на два случайных расположения атомов Mg
и Si, лишь одно из которых прошло всю лестницу, и по одному набору начальных
скоростей;""", "ru-realizations54")
t = sub(t, r"""уровень шума которого после усреднения шести компонент тензора по слою
составляет $0{,}5 \pm 0{,}6$~МПа.""",
        r"""разрешающая способность которого после усреднения шести компонент тензора
по слою составляет $2{,}5 \pm 0{,}5$~МПа.""", "ru-54noise")
save("Sections_4_ru.tex", t)

# ================================================================ main files and splice
p = PAPER / "main_ru.tex"; m = io.open(p, encoding="utf-8").read()
if "Конфликт интересов" not in m:
    m = m.replace("\\end{sloppypar}\n", "\\end{sloppypar}\n\n\\section*{Конфликт интересов}\nАвторы заявляют об отсутствии конфликта интересов.\n", 1)
    io.open(p, "w", encoding="utf-8", newline="\n").write(m)
p = PAPER / "splice_drafts.py"; s = io.open(p, encoding="utf-8").read()
s2 = s.replace('not ln.startswith("% \\\\todo")', 'not ln.startswith(r"% \\todo")')
s2 = s2.replace('not ln.startswith("\\\\providecommand{\\\\todo}")', 'not ln.startswith(r"\\providecommand{\\todo}")')
io.open(p, "w", encoding="utf-8", newline="\n").write(s2)

print("review fixes applied; unmatched:", rep if rep else "none")
